
import { Metadata } from "next"
export const metadata : Metadata= {
  title: {
    default:"Next.js Practice",
    template:"%s | Practice"

  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor:"green", 
            fontSize:"72px", 
            padding:"5%"
            }}>
            <p>Header</p>

          </header>
        {children}
        <footer style={{backgroundColor:"green", padding:"3rem"}}>
          <p>Footer</p>
        </footer>
      </body>
      
    </html>
  )
}
