export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <header
        style={{
          backgroundColor:"yellow", 
          fontSize:"20px"}}>
      </header>
      <body>{children}</body>
      <footer>
        footer
      </footer>
    </html>
  )
}
